# Generated by Django 4.0.5 on 2022-06-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpages', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContacIfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
        ),
    ]
