# Generated by Django 4.0.5 on 2022-06-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpages', '0003_contacifo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('synopsis', models.TextField()),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
